# This file configures the static analysis results for your project (errors,
# warnings, and lints).

include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_print
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - unnecessary_this
    - prefer_single_quotes
    - sort_constructors_first
    - unnecessary_late
    - avoid_unnecessary_containers
    - use_super_parameters

analyzer:
  errors:
    avoid_print: warning
